import {HorizontalMenuInterface} from '../components/molecules/Menu/HorizontalMenu';
import {CardNotificationAppsInterface} from '../components/molecules/Notification/CardNotificationApps';
import {PartyInterface} from '../interfaces/BookingInterface';
import {CoordinateInterface} from '../interfaces/Interface';
import {
  BillNotificationInterface,
  InvitationNotificationInterface,
} from '../interfaces/NotificationInterface';

import {
  PlaceOperationalTimeInterface,
  PlaceOverviewInterface,
} from '../interfaces/PlaceInterface';
import {DjRequestSongInterface} from '../interfaces/SongInterface';
import {
  FriendRequestInterface,
  UserAchievementInterface,
  UserInterface,
} from '../interfaces/UserInterface';

export const USER_ACHIEVEMENT: UserAchievementInterface = {
  currentLevel: 'VIP-GOLD',
  start: 2,
  end: 3,
  planLevel: 'Platinum',
};

export const Logo: Record<string, string> = {
  magnum:
    'https://wanderbucket.s3.ap-southeast-1.amazonaws.com/logo/magnum.png',
  empire:
    'https://wanderbucket.s3.ap-southeast-1.amazonaws.com/logo/empire.png',
  kor: 'https://wanderbucket.s3.ap-southeast-1.amazonaws.com/logo/kor.png',
  omni: 'https://wanderbucket.s3.ap-southeast-1.amazonaws.com/logo/omni.png',
  sax: 'https://wanderbucket.s3.ap-southeast-1.amazonaws.com/logo/sax.png',
  wrightAvenue:
    'https://wanderbucket.s3.ap-southeast-1.amazonaws.com/logo/wrightvenue.png',
};

export const PLACE_MENU: HorizontalMenuInterface[] = [
  {
    id: 1,
    title: 'Overview',
  },
  {
    id: 2,
    title: 'Offers',
  },
  {
    id: 3,
    title: 'Foods',
  },
  {
    id: 4,
    title: 'Photos',
  },
  {
    id: 5,
    title: 'Review',
  },
];

export const PLACE_MENU_SECOND: any[] = [
  {
    id: 1,
    title: 'Walk in Ticket',
  },
  {
    id: 2,
    title: 'Booking Table',
  },
];

export const PLACE_OVERVIEW: PlaceOverviewInterface = {
  about:
    'RUFF Taipei 創立於2020年9月提供HIP HOP 音樂，獨特的派對場地，歌手與藝術家，流行與潮流品牌，新鮮調酒與經典調酒等多元元素，座落於台北夜生活主要地點信義區，不定期舉辦特別活動。 歡迎熱愛HIP HOP及夜店文化的你／妳一同加入我們的大家庭。',
  features: [
    {
      title: 'Rated #1 Hiphop Nightclub in Taiwan',
      subtitle: 'Rated #1 Hiphop Nightclub in Taiwan',
      icon: 'rated',
    },
    {
      title: 'House Made Clothing Brand: Ruff Design',
      subtitle: 'Rated #1 Hiphop Nightclub in Taiwan',
      icon: 'clothing',
    },
    {
      title: 'Live performance for signers and rappers',
      subtitle: 'Rated #1 Hiphop Nightclub in Taiwan',
      icon: 'live',
    },
  ],
};

export const TODAY_APPS_NOTIFICATION: CardNotificationAppsInterface[] = [
  {
    image: Logo.sax,
    name: 'Sax Nightclub',
    ticket: 'Group Walk in',
    description:
      'confirmed your order for Check your my event page for get your ticket',
    date: '2023-08-10T13:10:03.650540055',
  },
  {
    image: Logo.empire,
    name: 'Empire Nightclub',
    ticket: 'Couple Group',
    description:
      'confirmed your order for Check your my event page for get your ticket',
    date: '2023-08-10T008:15:03.650540055',
  },
];

export const YESTERDAY_APPS_NOTIFICATION: CardNotificationAppsInterface[] = [
  {
    image: Logo.wrightAvenue,
    name: 'Wright Avenue',
    ticket: 'VIP Ticket',
    description:
      'confirmed your order for  Check your my event page for get your ticket',
    date: '2023-08-09T10:10:03.650540055',
  },
  {
    image: Logo.magnum,
    name: 'Magnum',
    ticket: 'Group Walk in',
    description:
      'confirmed your order for  Check your my event page for get your ticket',
    date: '2023-08-09T21:10:03.650540055',
  },
];

export const USER_DATA: UserInterface[] = [
  {
    id: '1',
    fullName: 'Lisandro',
    username: 'lisandro',
    phone: '0811111111',
    photoUrl:
      'https://s.hs-data.com/bilder/spieler/gross/376639.jpg?fallback=png',
    age: 26,
    bio: 'Just ordinary girl from ohama 🥰',
    email: 'lisandromartinez@gmail.com',
  },
  {
    id: '2',
    fullName: 'Mason Mount',
    username: 'mason_mount',
    phone: '0811111111',
    photoUrl:
      'https://s.hs-data.com/bilder/spieler/gross/337447.jpg?fallback=png',
    age: 22,
    bio: 'Just married',
    email: 'masonmount19@gmail.com',
  },
  {
    id: '3',
    fullName: 'Harry Maguire',
    username: 'h_maguire',
    phone: '0811111111',
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/header/177907-1663841733.jpg?lm=1',
    age: 32,
    bio: 'No  party without you 🥳',
    email: 'h_maguire@gmail.com',
  },
  {
    id: '4',
    fullName: 'Jill Valentine',
    username: 'jill_v66',
    phone: '0811111111',
    photoUrl:
      'https://e0.pxfuel.com/wallpapers/52/767/desktop-wallpaper-jill-valentine-in-resident-evil-3-remake-iphone-background-and-resident-evil-3-phone.jpg',
    age: 21,
    bio: 'Lets hang out',
    email: 'jill_v@gmail.com',
  },
  {
    id: '5',
    fullName: 'Tifa Lockhart',
    username: 'tiffa_ff',
    phone: '0811111111',
    photoUrl:
      'https://w0.peakpx.com/wallpaper/307/340/HD-wallpaper-tifa-lockhart-final-fantasy-vii.jpg',
    age: 21,
    bio: 'Lets drinks',
    email: 'tiffa@gmail.com',
  },
  {
    id: '6',
    fullName: 'Maria Mercedes',
    username: 'maria_77',
    phone: '0811111111',
    photoUrl:
      'https://i0.wp.com/media.ghgossip.com/wp-content/uploads/2022/11/10192356/maria.jpg?resize=488%2C629&ssl=1',
  },
];

export const PARTY_DATA: PartyInterface[] = [
  {
    id: 'ABC',
    name: 'Wave Taipei',
    logo: Logo.sax,
    ticket: 'VIP Ticket',
    date: '2023-08-19T022:15:03.650540055',
    quota: 10,
    joined: 0,
    table: 'Table X4',
  },
  {
    id: 'DEF',
    name: 'Levels Nightclub',
    logo: 'https://www.pickfu.com/blog/wp-content/uploads/2019/04/nightclub-logo-design-1.png',
    ticket: 'VIP Ticket',
    date: '2023-08-19T023:15:03.650540055',
    quota: 6,
    joined: 2,
    table: 'Table Z2',
  },
];

export const INVITATION_NOTIFICATION: InvitationNotificationInterface[] = [
  {
    id: '1',
    sender: {
      id: '5',
      fullName: 'Tifa Lockhart',
      username: 'tiffa_ff',
      phone: '0811111111',
      photoUrl:
        'https://w0.peakpx.com/wallpaper/307/340/HD-wallpaper-tifa-lockhart-final-fantasy-vii.jpg',
      age: 21,
      bio: 'Lets drinks',
      email: 'tiffa@gmail.com',
    },
    message:
      'Hi michael, i’m Tifa who meet you at the wave. Would you come to my table at ruff ? we will arrived around 11am ❤️',
    date: '2023-08-10T008:15:03.650540055',
    party: {
      id: 'ABC',
      name: 'Wave Taipei',
      logo: Logo.sax,
      ticket: 'VIP Ticket',
      date: '2023-08-14T010:15:03.650540055',
      quota: 10,
      joined: 5,
      table: 'Table X4',
    },
  },

  {
    id: '2',
    sender: {
      id: '4',
      fullName: 'Jill Valentine',
      username: 'jill_v66',
      phone: '0811111111',
      photoUrl:
        'https://e0.pxfuel.com/wallpapers/52/767/desktop-wallpaper-jill-valentine-in-resident-evil-3-remake-iphone-background-and-resident-evil-3-phone.jpg',
      age: 21,
      bio: 'Lets hang out',
      email: 'jill_v@gmail.com',
    },
    message:
      'Hi michael, i’m Jill who meet you at the wave. Would you come to my table at ruff ? we will arrived around 11am ❤️',
    date: '2023-08-10T010:15:03.650540055',
    party: {
      id: 'DEF',
      name: 'Levels Nightclub',
      logo: 'https://www.pickfu.com/blog/wp-content/uploads/2019/04/nightclub-logo-design-1.png',
      ticket: 'VIP Ticket',
      date: '2023-08-19T010:15:03.650540055',
      quota: 6,
      joined: 1,
      table: 'Table Z2',
    },
  },
  {
    id: '3',
    sender: {
      id: '3',
      fullName: 'Harry Maguire',
      username: 'h_maguire',
      phone: '0811111111',
      photoUrl:
        'https://img.a.transfermarkt.technology/portrait/header/177907-1663841733.jpg?lm=1',
      age: 32,
      bio: 'No  party without you 🥳',
      email: 'h_maguire@gmail.com',
    },
    message:
      'Hi michael, i’m Maguire who meet you at the wave. Would you come to my table at ruff ? we will arrived around 11am ❤️',
    date: '2023-08-10T014:15:03.650540055',
    party: {
      id: 'ABC',
      name: 'Wright Avenue',
      logo: Logo.wrightAvenue,
      ticket: 'VIP Ticket',
      date: '2023-08-25T010:15:03.650540055',
      quota: 6,
      joined: 4,
      table: 'Table Z2',
    },
  },
  {
    id: '4',
    sender: {
      id: '2',
      fullName: 'Mason Mount',
      username: 'mason_mount',
      phone: '0811111111',
      photoUrl:
        'https://s.hs-data.com/bilder/spieler/gross/337447.jpg?fallback=png',
      age: 22,
      bio: 'Just married',
      email: 'masonmount19@gmail.com',
    },
    message:
      'Hi michael, i’m Mason who meet you at the wave. Would you come to my table at ruff ? we will arrived around 11am ❤️',
    date: '2023-08-10T018:15:03.650540055',
    party: {
      id: 'DEF',
      name: 'Magnum Nightclub',
      logo: Logo.magnum,
      ticket: 'VIP Ticket',
      date: '2023-08-26T010:15:03.650540055',
      quota: 6,
      joined: 3,
      table: 'Table Z2',
    },
  },
];

export const BILL_NOTIFICATION: BillNotificationInterface[] = [
  {
    id: 'aaa',
    billNumber: 'WV99920-21',
    hosted: 'Jean Chen',
    booking: {
      id: 'ABC',
      name: 'Wave Taipei',
      logo: Logo.sax,
      ticket: 'VIP Ticket',
      date: '2023-08-19T022:15:03.650540055',
      quota: 10,
      joined: 0,
      table: 'Table X4',
    },
    price: 12000,
    isSplitBill: true,
    isFoodOrder: true,
    date: '2023-08-14T010:15:03.650540055',
  },
  {
    id: 'bbb',
    billNumber: 'WV99920-32',
    hosted: 'Jean Chen',
    booking: {
      id: 'CBA',
      name: 'Wave Taipei',
      logo: Logo.sax,
      ticket: 'VIP Ticket',
      date: '2023-08-26T022:15:03.650540055',
      quota: 5,
      joined: 2,
      table: 'Table Z1',
    },
    price: 20000,
    isSplitBill: false,
    isFoodOrder: true,
    date: '2023-08-19T010:15:03.650540055',
  },
  {
    id: 'ccc',
    billNumber: 'LN99923-11',
    hosted: 'Jean Chen',
    booking: {
      id: 'DEF',
      name: 'Levels Nightclub',
      logo: 'https://www.pickfu.com/blog/wp-content/uploads/2019/04/nightclub-logo-design-1.png',
      ticket: 'VIP Ticket',
      date: '2023-08-27T023:15:03.650540055',
      quota: 6,
      joined: 2,
      table: 'Table Z2',
    },
    price: 8000,
    isSplitBill: true,
    isFoodOrder: false,
    date: '2023-08-10T014:15:03.650540055',
  },
  {
    id: 'ddd',
    billNumber: 'LN99924-27',
    hosted: 'Jean Chen',
    booking: {
      id: 'FED',
      name: 'Levels Nightclub',
      logo: 'https://www.pickfu.com/blog/wp-content/uploads/2019/04/nightclub-logo-design-1.png',
      ticket: 'VIP Ticket',
      date: '2023-08-20T023:15:03.650540055',
      quota: 8,
      joined: 5,
      table: 'Table K7',
    },
    price: 12000,
    isSplitBill: true,
    isFoodOrder: true,
    date: '2023-08-26T010:15:03.650540055',
  },
];

export const FRIEND_REQUEST: FriendRequestInterface[] = [
  {
    id: '1',
    name: 'Jill Valentine',
    photoUrl:
      'https://e0.pxfuel.com/wallpapers/52/767/desktop-wallpaper-jill-valentine-in-resident-evil-3-remake-iphone-background-and-resident-evil-3-phone.jpg',
    date: '2023-08-10T010:15:03.650540055',
  },
  {
    id: '2',
    name: 'Lisandro',
    photoUrl:
      'https://s.hs-data.com/bilder/spieler/gross/376639.jpg?fallback=png',
    date: '2023-08-11T010:15:03.650540055',
  },
  {
    id: '3',
    name: 'Harry Maguire',
    photoUrl:
      'https://img.a.transfermarkt.technology/portrait/header/177907-1663841733.jpg?lm=1',
    date: '2023-08-11T022:15:03.650540055',
  },
  {
    id: '4',
    name: 'Mason Mount',
    photoUrl:
      'https://s.hs-data.com/bilder/spieler/gross/337447.jpg?fallback=png',
    date: '2023-08-13T012:15:03.650540055',
  },
  {
    id: '5',
    name: 'Tifa Lockhart',
    photoUrl:
      'https://w0.peakpx.com/wallpaper/307/340/HD-wallpaper-tifa-lockhart-final-fantasy-vii.jpg',
    date: '2023-08-02T010:15:03.650540055',
  },
];

export const OPERATIONAL_TIME_DATA: PlaceOperationalTimeInterface[] = [
  {
    day: 'Monday',
    open: '10 pm',
    close: '4 am',
    isClose: false,
  },
  {
    day: 'Tuesday',
    open: '10 pm',
    close: '4 am',
    isClose: false,
  },
  {
    day: 'Wednesday',
    open: '10 pm',
    close: '4 am',
    isClose: false,
  },
  {
    day: 'Thursday',
    open: null,
    close: null,
    isClose: true,
  },
  {
    day: 'Friday',
    open: '10 pm',
    close: '4 am',
    isClose: false,
  },
  {
    day: 'Saturday',
    open: null,
    close: null,
    isClose: true,
  },
  {
    day: 'Sunday',
    open: '10 pm',
    close: '4 am',
    isClose: false,
  },
];

export const INVITE_FRIENDS_TEXT: string[] = [
  'Attending an event solo can sometimes feel dull and cost more. However, when you come with friends, the experience becomes more enjoyable and budget-friendly.',
  'With our group ticket option, you not only secure a reduced price but also have the chance to invite your pals along. As the organizer,',
  "you'll initially cover the group ticket cost, and we'll help you generate invoices for your friends.",
  'Get ready for an amazing party experience and let loose on the dance floor!',
];

export const WAITING_LIST_TEXT: string[] = [
  'Attending an event solo can sometimes feel dull and cost more. However, when you come with friends, the experience becomes more enjoyable and budget-friendly.',
  'With our group ticket option, you not only secure a reduced price but also have the chance to invite your pals along. As the organizer, ',
  "you'll initially cover the group ticket cost, and we'll help you generate invoices for your friends.",
  'Get ready for an amazing party experience and let loose on the dance floor!',
];

export const DJ_REQUEST_DATA: DjRequestSongInterface[] = [
  {
    title: 'Separuh Nafas',
    artis: 'Dewa 19',
    fee: 1000,
    requestedName: 'Reza',
    requestedPhotoUrl:
      'https://djmag.com/sites/default/files/styles/djm_23_1005x565/public/2022-06/unnamed_3.jpeg.webp?itok=fhBZmcG3',
  },
  {
    title: 'You',
    artis: 'Lost Frequencies',
    fee: 750,
    requestedName: 'Daniel',
    requestedPhotoUrl:
      'https://s.hs-data.com/bilder/spieler/gross/337447.jpg?fallback=png',
  },
  {
    title: 'Flamingo',
    artis: 'Oliver Heldens',
    fee: 1300,
    requestedName: 'Reza',
    requestedPhotoUrl:
      'https://djmag.com/sites/default/files/styles/djm_23_1005x565/public/2022-06/unnamed_3.jpeg.webp?itok=fhBZmcG3',
  },
  {
    title: 'Hippo',
    artis: 'Chocolate Puma',
    fee: 500,
    requestedName: 'Reza',
    requestedPhotoUrl:
      'https://djmag.com/sites/default/files/styles/djm_23_1005x565/public/2022-06/unnamed_3.jpeg.webp?itok=fhBZmcG3',
  },
  {
    title: 'Beats Knockin',
    artis: 'Skrillex',
    fee: 3000,
    requestedName: 'Reza',
    requestedPhotoUrl:
      'https://djmag.com/sites/default/files/styles/djm_23_1005x565/public/2022-06/unnamed_3.jpeg.webp?itok=fhBZmcG3',
  },
];

export const CITY_SAMPLE_DATA = [
  'Taoyuan',
  'Taichung',
  'Yilang',
  'Changhua',
  'Chiayi',
  'Kinmen',
];

export const COORDINATE_DATA: CoordinateInterface[] = [
  {
    latitude: -7.725,
    longitude: 112.589444,
  },
  {
    latitude: -8.021875,
    longitude: 112.952438,
  },
  {
    latitude: -7.741727,
    longitude: 112.534377,
  },
  {
    latitude: -7.969469,
    longitude: 112.802997,
  },
  {
    latitude: -7.725,
    longitude: 112.589444,
  },
  {
    latitude: -7.911625,
    longitude: 112.520709,
  },
  {
    latitude: -8.021806,
    longitude: 112.835899,
  },
  {
    latitude: -7.797779,
    longitude: 112.736859,
  },
  {
    latitude: -7.904167,
    longitude: 112.496667,
  },
  {
    latitude: -8.436944,
    longitude: 112.641667,
  },
];

export const COUNTRY_PHONE_CODE_WITH_ICON = [
  {name: 'Afghanistan', flag: '🇦🇫', code: 'AF', dial_code: '+93'},
  {name: 'Åland Islands', flag: '🇦🇽', code: 'AX', dial_code: '+358'},
  {name: 'Albania', flag: '🇦🇱', code: 'AL', dial_code: '+355'},
  {name: 'Algeria', flag: '🇩🇿', code: 'DZ', dial_code: '+213'},
  {name: 'American Samoa', flag: '🇦🇸', code: 'AS', dial_code: '+1684'},
  {name: 'Andorra', flag: '🇦🇩', code: 'AD', dial_code: '+376'},
  {name: 'Angola', flag: '🇦🇴', code: 'AO', dial_code: '+244'},
  {name: 'Anguilla', flag: '🇦🇮', code: 'AI', dial_code: '+1264'},
  {name: 'Antarctica', flag: '🇦🇶', code: 'AQ', dial_code: '+672'},
  {name: 'Antigua and Barbuda', flag: '🇦🇬', code: 'AG', dial_code: '+1268'},
  {name: 'Argentina', flag: '🇦🇷', code: 'AR', dial_code: '+54'},
  {name: 'Armenia', flag: '🇦🇲', code: 'AM', dial_code: '+374'},
  {name: 'Aruba', flag: '🇦🇼', code: 'AW', dial_code: '+297'},
  {name: 'Australia', flag: '🇦🇺', code: 'AU', dial_code: '+61'},
  {name: 'Austria', flag: '🇦🇹', code: 'AT', dial_code: '+43'},
  {name: 'Azerbaijan', flag: '🇦🇿', code: 'AZ', dial_code: '+994'},
  {name: 'Bahamas', flag: '🇧🇸', code: 'BS', dial_code: '+1242'},
  {name: 'Bahrain', flag: '🇧🇭', code: 'BH', dial_code: '+973'},
  {name: 'Bangladesh', flag: '🇧🇩', code: 'BD', dial_code: '+880'},
  {name: 'Barbados', flag: '🇧🇧', code: 'BB', dial_code: '+1246'},
  {name: 'Belarus', flag: '🇧🇾', code: 'BY', dial_code: '+375'},
  {name: 'Belgium', flag: '🇧🇪', code: 'BE', dial_code: '+32'},
  {name: 'Belize', flag: '🇧🇿', code: 'BZ', dial_code: '+501'},
  {name: 'Benin', flag: '🇧🇯', code: 'BJ', dial_code: '+229'},
  {name: 'Bermuda', flag: '🇧🇲', code: 'BM', dial_code: '+1441'},
  {name: 'Bhutan', flag: '🇧🇹', code: 'BT', dial_code: '+975'},
  {
    name: 'Bolivia, Plurinational State of bolivia',
    flag: '🇧🇴',
    code: 'BO',
    dial_code: '+591',
  },
  {name: 'Bosnia and Herzegovina', flag: '🇧🇦', code: 'BA', dial_code: '+387'},
  {name: 'Botswana', flag: '🇧🇼', code: 'BW', dial_code: '+267'},
  {name: 'Bouvet Island', flag: '🇧🇻', code: 'BV', dial_code: '+47'},
  {name: 'Brazil', flag: '🇧🇷', code: 'BR', dial_code: '+55'},
  {
    name: 'British Indian Ocean Territory',
    flag: '🇮🇴',
    code: 'IO',
    dial_code: '+246',
  },
  {name: 'Brunei Darussalam', flag: '🇧🇳', code: 'BN', dial_code: '+673'},
  {name: 'Bulgaria', flag: '🇧🇬', code: 'BG', dial_code: '+359'},
  {name: 'Burkina Faso', flag: '🇧🇫', code: 'BF', dial_code: '+226'},
  {name: 'Burundi', flag: '🇧🇮', code: 'BI', dial_code: '+257'},
  {name: 'Cambodia', flag: '🇰🇭', code: 'KH', dial_code: '+855'},
  {name: 'Cameroon', flag: '🇨🇲', code: 'CM', dial_code: '+237'},
  {name: 'Canada', flag: '🇨🇦', code: 'CA', dial_code: '+1'},
  {name: 'Cape Verde', flag: '🇨🇻', code: 'CV', dial_code: '+238'},
  {name: 'Cayman Islands', flag: '🇰🇾', code: 'KY', dial_code: '+345'},
  {name: 'Central African Republic', flag: '🇨🇫', code: 'CF', dial_code: '+236'},
  {name: 'Chad', flag: '🇹🇩', code: 'TD', dial_code: '+235'},
  {name: 'Chile', flag: '🇨🇱', code: 'CL', dial_code: '+56'},
  {name: 'China', flag: '🇨🇳', code: 'CN', dial_code: '+86'},
  {name: 'Christmas Island', flag: '🇨🇽', code: 'CX', dial_code: '+61'},
  {name: 'Cocos (Keeling) Islands', flag: '🇨🇨', code: 'CC', dial_code: '+61'},
  {name: 'Colombia', flag: '🇨🇴', code: 'CO', dial_code: '+57'},
  {name: 'Comoros', flag: '🇰🇲', code: 'KM', dial_code: '+269'},
  {name: 'Congo', flag: '🇨🇬', code: 'CG', dial_code: '+242'},
  {
    name: 'Congo, The Democratic Republic of the Congo',
    flag: '🇨🇩',
    code: 'CD',
    dial_code: '+243',
  },
  {name: 'Cook Islands', flag: '🇨🇰', code: 'CK', dial_code: '+682'},
  {name: 'Costa Rica', flag: '🇨🇷', code: 'CR', dial_code: '+506'},
  {name: "Cote d'Ivoire", flag: '🇨🇮', code: 'CI', dial_code: '+225'},
  {name: 'Croatia', flag: '🇭🇷', code: 'HR', dial_code: '+385'},
  {name: 'Cuba', flag: '🇨🇺', code: 'CU', dial_code: '+53'},
  {name: 'Cyprus', flag: '🇨🇾', code: 'CY', dial_code: '+357'},
  {name: 'Czech Republic', flag: '🇨🇿', code: 'CZ', dial_code: '+420'},
  {name: 'Denmark', flag: '🇩🇰', code: 'DK', dial_code: '+45'},
  {name: 'Djibouti', flag: '🇩🇯', code: 'DJ', dial_code: '+253'},
  {name: 'Dominica', flag: '🇩🇲', code: 'DM', dial_code: '+1767'},
  {name: 'Dominican Republic', flag: '🇩🇴', code: 'DO', dial_code: '+1849'},
  {name: 'Ecuador', flag: '🇪🇨', code: 'EC', dial_code: '+593'},
  {name: 'Egypt', flag: '🇪🇬', code: 'EG', dial_code: '+20'},
  {name: 'El Salvador', flag: '🇸🇻', code: 'SV', dial_code: '+503'},
  {name: 'Equatorial Guinea', flag: '🇬🇶', code: 'GQ', dial_code: '+240'},
  {name: 'Eritrea', flag: '🇪🇷', code: 'ER', dial_code: '+291'},
  {name: 'Estonia', flag: '🇪🇪', code: 'EE', dial_code: '+372'},
  {name: 'Ethiopia', flag: '🇪🇹', code: 'ET', dial_code: '+251'},
  {
    name: 'Falkland Islands (Malvinas)',
    flag: '🇫🇰',
    code: 'FK',
    dial_code: '+500',
  },
  {name: 'Faroe Islands', flag: '🇫🇴', code: 'FO', dial_code: '+298'},
  {name: 'Fiji', flag: '🇫🇯', code: 'FJ', dial_code: '+679'},
  {name: 'Finland', flag: '🇫🇮', code: 'FI', dial_code: '+358'},
  {name: 'France', flag: '🇫🇷', code: 'FR', dial_code: '+33'},
  {name: 'French Guiana', flag: '🇬🇫', code: 'GF', dial_code: '+594'},
  {name: 'French Polynesia', flag: '🇵🇫', code: 'PF', dial_code: '+689'},
  {
    name: 'French Southern Territories',
    flag: '🇹🇫',
    code: 'TF',
    dial_code: '+262',
  },
  {name: 'Gabon', flag: '🇬🇦', code: 'GA', dial_code: '+241'},
  {name: 'Gambia', flag: '🇬🇲', code: 'GM', dial_code: '+220'},
  {name: 'Georgia', flag: '🇬🇪', code: 'GE', dial_code: '+995'},
  {name: 'Germany', flag: '🇩🇪', code: 'DE', dial_code: '+49'},
  {name: 'Ghana', flag: '🇬🇭', code: 'GH', dial_code: '+233'},
  {name: 'Gibraltar', flag: '🇬🇮', code: 'GI', dial_code: '+350'},
  {name: 'Greece', flag: '🇬🇷', code: 'GR', dial_code: '+30'},
  {name: 'Greenland', flag: '🇬🇱', code: 'GL', dial_code: '+299'},
  {name: 'Grenada', flag: '🇬🇩', code: 'GD', dial_code: '+1473'},
  {name: 'Guadeloupe', flag: '🇬🇵', code: 'GP', dial_code: '+590'},
  {name: 'Guam', flag: '🇬🇺', code: 'GU', dial_code: '+1671'},
  {name: 'Guatemala', flag: '🇬🇹', code: 'GT', dial_code: '+502'},
  {name: 'Guernsey', flag: '🇬🇬', code: 'GG', dial_code: '+44'},
  {name: 'Guinea', flag: '🇬🇳', code: 'GN', dial_code: '+224'},
  {name: 'Guinea-Bissau', flag: '🇬🇼', code: 'GW', dial_code: '+245'},
  {name: 'Guyana', flag: '🇬🇾', code: 'GY', dial_code: '+592'},
  {name: 'Haiti', flag: '🇭🇹', code: 'HT', dial_code: '+509'},
  {
    name: 'Heard Island and Mcdonald Islands',
    flag: '🇭🇲',
    code: 'HM',
    dial_code: '+672',
  },
  {
    name: 'Holy See (Vatican City State)',
    flag: '🇻🇦',
    code: 'VA',
    dial_code: '+379',
  },
  {name: 'Honduras', flag: '🇭🇳', code: 'HN', dial_code: '+504'},
  {name: 'Hong Kong', flag: '🇭🇰', code: 'HK', dial_code: '+852'},
  {name: 'Hungary', flag: '🇭🇺', code: 'HU', dial_code: '+36'},
  {name: 'Iceland', flag: '🇮🇸', code: 'IS', dial_code: '+354'},
  {name: 'India', flag: '🇮🇳', code: 'IN', dial_code: '+91'},
  {name: 'Indonesia', flag: '🇮🇩', code: 'ID', dial_code: '+62'},
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    flag: '🇮🇷',
    code: 'IR',
    dial_code: '+98',
  },
  {name: 'Iraq', flag: '🇮🇶', code: 'IQ', dial_code: '+964'},
  {name: 'Ireland', flag: '🇮🇪', code: 'IE', dial_code: '+353'},
  {name: 'Isle of Man', flag: '🇮🇲', code: 'IM', dial_code: '+44'},
  {name: 'Israel', flag: '🇮🇱', code: 'IL', dial_code: '+972'},
  {name: 'Italy', flag: '🇮🇹', code: 'IT', dial_code: '+39'},
  {name: 'Jamaica', flag: '🇯🇲', code: 'JM', dial_code: '+1876'},
  {name: 'Japan', flag: '🇯🇵', code: 'JP', dial_code: '+81'},
  {name: 'Jersey', flag: '🇯🇪', code: 'JE', dial_code: '+44'},
  {name: 'Jordan', flag: '🇯🇴', code: 'JO', dial_code: '+962'},
  {name: 'Kazakhstan', flag: '🇰🇿', code: 'KZ', dial_code: '+7'},
  {name: 'Kenya', flag: '🇰🇪', code: 'KE', dial_code: '+254'},
  {name: 'Kiribati', flag: '🇰🇮', code: 'KI', dial_code: '+686'},
  {
    name: "Korea, Democratic People's Republic of Korea",
    flag: '🇰🇵',
    code: 'KP',
    dial_code: '+850',
  },
  {
    name: 'Korea, Republic of South Korea',
    flag: '🇰🇷',
    code: 'KR',
    dial_code: '+82',
  },
  {name: 'Kosovo', flag: '🇽🇰', code: 'XK', dial_code: '+383'},
  {name: 'Kuwait', flag: '🇰🇼', code: 'KW', dial_code: '+965'},
  {name: 'Kyrgyzstan', flag: '🇰🇬', code: 'KG', dial_code: '+996'},
  {name: 'Laos', flag: '🇱🇦', code: 'LA', dial_code: '+856'},
  {name: 'Latvia', flag: '🇱🇻', code: 'LV', dial_code: '+371'},
  {name: 'Lebanon', flag: '🇱🇧', code: 'LB', dial_code: '+961'},
  {name: 'Lesotho', flag: '🇱🇸', code: 'LS', dial_code: '+266'},
  {name: 'Liberia', flag: '🇱🇷', code: 'LR', dial_code: '+231'},
  {name: 'Libyan Arab Jamahiriya', flag: '🇱🇾', code: 'LY', dial_code: '+218'},
  {name: 'Liechtenstein', flag: '🇱🇮', code: 'LI', dial_code: '+423'},
  {name: 'Lithuania', flag: '🇱🇹', code: 'LT', dial_code: '+370'},
  {name: 'Luxembourg', flag: '🇱🇺', code: 'LU', dial_code: '+352'},
  {name: 'Macao', flag: '🇲🇴', code: 'MO', dial_code: '+853'},
  {name: 'Macedonia', flag: '🇲🇰', code: 'MK', dial_code: '+389'},
  {name: 'Madagascar', flag: '🇲🇬', code: 'MG', dial_code: '+261'},
  {name: 'Malawi', flag: '🇲🇼', code: 'MW', dial_code: '+265'},
  {name: 'Malaysia', flag: '🇲🇾', code: 'MY', dial_code: '+60'},
  {name: 'Maldives', flag: '🇲🇻', code: 'MV', dial_code: '+960'},
  {name: 'Mali', flag: '🇲🇱', code: 'ML', dial_code: '+223'},
  {name: 'Malta', flag: '🇲🇹', code: 'MT', dial_code: '+356'},
  {name: 'Marshall Islands', flag: '🇲🇭', code: 'MH', dial_code: '+692'},
  {name: 'Martinique', flag: '🇲🇶', code: 'MQ', dial_code: '+596'},
  {name: 'Mauritania', flag: '🇲🇷', code: 'MR', dial_code: '+222'},
  {name: 'Mauritius', flag: '🇲🇺', code: 'MU', dial_code: '+230'},
  {name: 'Mayotte', flag: '🇾🇹', code: 'YT', dial_code: '+262'},
  {name: 'Mexico', flag: '🇲🇽', code: 'MX', dial_code: '+52'},
  {
    name: 'Micronesia, Federated States of Micronesia',
    flag: '🇫🇲',
    code: 'FM',
    dial_code: '+691',
  },
  {name: 'Moldova', flag: '🇲🇩', code: 'MD', dial_code: '+373'},
  {name: 'Monaco', flag: '🇲🇨', code: 'MC', dial_code: '+377'},
  {name: 'Mongolia', flag: '🇲🇳', code: 'MN', dial_code: '+976'},
  {name: 'Montenegro', flag: '🇲🇪', code: 'ME', dial_code: '+382'},
  {name: 'Montserrat', flag: '🇲🇸', code: 'MS', dial_code: '+1664'},
  {name: 'Morocco', flag: '🇲🇦', code: 'MA', dial_code: '+212'},
  {name: 'Mozambique', flag: '🇲🇿', code: 'MZ', dial_code: '+258'},
  {name: 'Myanmar', flag: '🇲🇲', code: 'MM', dial_code: '+95'},
  {name: 'Namibia', flag: '🇳🇦', code: 'NA', dial_code: '+264'},
  {name: 'Nauru', flag: '🇳🇷', code: 'NR', dial_code: '+674'},
  {name: 'Nepal', flag: '🇳🇵', code: 'NP', dial_code: '+977'},
  {name: 'Netherlands', flag: '🇳🇱', code: 'NL', dial_code: '+31'},
  {name: 'Netherlands Antilles', flag: '', code: 'AN', dial_code: '+599'},
  {name: 'New Caledonia', flag: '🇳🇨', code: 'NC', dial_code: '+687'},
  {name: 'New Zealand', flag: '🇳🇿', code: 'NZ', dial_code: '+64'},
  {name: 'Nicaragua', flag: '🇳🇮', code: 'NI', dial_code: '+505'},
  {name: 'Niger', flag: '🇳🇪', code: 'NE', dial_code: '+227'},
  {name: 'Nigeria', flag: '🇳🇬', code: 'NG', dial_code: '+234'},
  {name: 'Niue', flag: '🇳🇺', code: 'NU', dial_code: '+683'},
  {name: 'Norfolk Island', flag: '🇳🇫', code: 'NF', dial_code: '+672'},
  {
    name: 'Northern Mariana Islands',
    flag: '🇲🇵',
    code: 'MP',
    dial_code: '+1670',
  },
  {name: 'Norway', flag: '🇳🇴', code: 'NO', dial_code: '+47'},
  {name: 'Oman', flag: '🇴🇲', code: 'OM', dial_code: '+968'},
  {name: 'Pakistan', flag: '🇵🇰', code: 'PK', dial_code: '+92'},
  {name: 'Palau', flag: '🇵🇼', code: 'PW', dial_code: '+680'},
  {
    name: 'Palestinian Territory, Occupied',
    flag: '🇵🇸',
    code: 'PS',
    dial_code: '+970',
  },
  {name: 'Panama', flag: '🇵🇦', code: 'PA', dial_code: '+507'},
  {name: 'Papua New Guinea', flag: '🇵🇬', code: 'PG', dial_code: '+675'},
  {name: 'Paraguay', flag: '🇵🇾', code: 'PY', dial_code: '+595'},
  {name: 'Peru', flag: '🇵🇪', code: 'PE', dial_code: '+51'},
  {name: 'Philippines', flag: '🇵🇭', code: 'PH', dial_code: '+63'},
  {name: 'Pitcairn', flag: '🇵🇳', code: 'PN', dial_code: '+64'},
  {name: 'Poland', flag: '🇵🇱', code: 'PL', dial_code: '+48'},
  {name: 'Portugal', flag: '🇵🇹', code: 'PT', dial_code: '+351'},
  {name: 'Puerto Rico', flag: '🇵🇷', code: 'PR', dial_code: '+1939'},
  {name: 'Qatar', flag: '🇶🇦', code: 'QA', dial_code: '+974'},
  {name: 'Romania', flag: '🇷🇴', code: 'RO', dial_code: '+40'},
  {name: 'Russia', flag: '🇷🇺', code: 'RU', dial_code: '+7'},
  {name: 'Rwanda', flag: '🇷🇼', code: 'RW', dial_code: '+250'},
  {name: 'Reunion', flag: '🇷🇪', code: 'RE', dial_code: '+262'},
  {name: 'Saint Barthelemy', flag: '🇧🇱', code: 'BL', dial_code: '+590'},
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    flag: '🇸🇭',
    code: 'SH',
    dial_code: '+290',
  },
  {name: 'Saint Kitts and Nevis', flag: '🇰🇳', code: 'KN', dial_code: '+1869'},
  {name: 'Saint Lucia', flag: '🇱🇨', code: 'LC', dial_code: '+1758'},
  {name: 'Saint Martin', flag: '🇲🇫', code: 'MF', dial_code: '+590'},
  {
    name: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
    code: 'PM',
    dial_code: '+508',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
    code: 'VC',
    dial_code: '+1784',
  },
  {name: 'Samoa', flag: '🇼🇸', code: 'WS', dial_code: '+685'},
  {name: 'San Marino', flag: '🇸🇲', code: 'SM', dial_code: '+378'},
  {name: 'Sao Tome and Principe', flag: '🇸🇹', code: 'ST', dial_code: '+239'},
  {name: 'Saudi Arabia', flag: '🇸🇦', code: 'SA', dial_code: '+966'},
  {name: 'Senegal', flag: '🇸🇳', code: 'SN', dial_code: '+221'},
  {name: 'Serbia', flag: '🇷🇸', code: 'RS', dial_code: '+381'},
  {name: 'Seychelles', flag: '🇸🇨', code: 'SC', dial_code: '+248'},
  {name: 'Sierra Leone', flag: '🇸🇱', code: 'SL', dial_code: '+232'},
  {name: 'Singapore', flag: '🇸🇬', code: 'SG', dial_code: '+65'},
  {name: 'Slovakia', flag: '🇸🇰', code: 'SK', dial_code: '+421'},
  {name: 'Slovenia', flag: '🇸🇮', code: 'SI', dial_code: '+386'},
  {name: 'Solomon Islands', flag: '🇸🇧', code: 'SB', dial_code: '+677'},
  {name: 'Somalia', flag: '🇸🇴', code: 'SO', dial_code: '+252'},
  {name: 'South Africa', flag: '🇿🇦', code: 'ZA', dial_code: '+27'},
  {name: 'South Sudan', flag: '🇸🇸', code: 'SS', dial_code: '+211'},
  {
    name: 'South Georgia and the South Sandwich Islands',
    flag: '🇬🇸',
    code: 'GS',
    dial_code: '+500',
  },
  {name: 'Spain', flag: '🇪🇸', code: 'ES', dial_code: '+34'},
  {name: 'Sri Lanka', flag: '🇱🇰', code: 'LK', dial_code: '+94'},
  {name: 'Sudan', flag: '🇸🇩', code: 'SD', dial_code: '+249'},
  {name: 'Suriname', flag: '🇸🇷', code: 'SR', dial_code: '+597'},
  {name: 'Svalbard and Jan Mayen', flag: '🇸🇯', code: 'SJ', dial_code: '+47'},
  {name: 'Eswatini', flag: '🇸🇿', code: 'SZ', dial_code: '+268'},
  {name: 'Sweden', flag: '🇸🇪', code: 'SE', dial_code: '+46'},
  {name: 'Switzerland', flag: '🇨🇭', code: 'CH', dial_code: '+41'},
  {name: 'Syrian Arab Republic', flag: '🇸🇾', code: 'SY', dial_code: '+963'},
  {name: 'Taiwan', flag: '🇹🇼', code: 'TW', dial_code: '+886'},
  {name: 'Tajikistan', flag: '🇹🇯', code: 'TJ', dial_code: '+992'},
  {
    name: 'Tanzania, United Republic of Tanzania',
    flag: '🇹🇿',
    code: 'TZ',
    dial_code: '+255',
  },
  {name: 'Thailand', flag: '🇹🇭', code: 'TH', dial_code: '+66'},
  {name: 'Timor-Leste', flag: '🇹🇱', code: 'TL', dial_code: '+670'},
  {name: 'Togo', flag: '🇹🇬', code: 'TG', dial_code: '+228'},
  {name: 'Tokelau', flag: '🇹🇰', code: 'TK', dial_code: '+690'},
  {name: 'Tonga', flag: '🇹🇴', code: 'TO', dial_code: '+676'},
  {name: 'Trinidad and Tobago', flag: '🇹🇹', code: 'TT', dial_code: '+1868'},
  {name: 'Tunisia', flag: '🇹🇳', code: 'TN', dial_code: '+216'},
  {name: 'Turkey', flag: '🇹🇷', code: 'TR', dial_code: '+90'},
  {name: 'Turkmenistan', flag: '🇹🇲', code: 'TM', dial_code: '+993'},
  {
    name: 'Turks and Caicos Islands',
    flag: '🇹🇨',
    code: 'TC',
    dial_code: '+1649',
  },
  {name: 'Tuvalu', flag: '🇹🇻', code: 'TV', dial_code: '+688'},
  {name: 'Uganda', flag: '🇺🇬', code: 'UG', dial_code: '+256'},
  {name: 'Ukraine', flag: '🇺🇦', code: 'UA', dial_code: '+380'},
  {name: 'United Arab Emirates', flag: '🇦🇪', code: 'AE', dial_code: '+971'},
  {name: 'United Kingdom', flag: '🇬🇧', code: 'GB', dial_code: '+44'},
  {name: 'United States', flag: '🇺🇸', code: 'US', dial_code: '+1'},
  {name: 'Uruguay', flag: '🇺🇾', code: 'UY', dial_code: '+598'},
  {name: 'Uzbekistan', flag: '🇺🇿', code: 'UZ', dial_code: '+998'},
  {name: 'Vanuatu', flag: '🇻🇺', code: 'VU', dial_code: '+678'},
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    flag: '🇻🇪',
    code: 'VE',
    dial_code: '+58',
  },
  {name: 'Vietnam', flag: '🇻🇳', code: 'VN', dial_code: '+84'},
  {name: 'Virgin Islands, British', flag: '🇻🇬', code: 'VG', dial_code: '+1284'},
  {name: 'Virgin Islands, U.S.', flag: '🇻🇮', code: 'VI', dial_code: '+1340'},
  {name: 'Wallis and Futuna', flag: '🇼🇫', code: 'WF', dial_code: '+681'},
  {name: 'Yemen', flag: '🇾🇪', code: 'YE', dial_code: '+967'},
  {name: 'Zambia', flag: '🇿🇲', code: 'ZM', dial_code: '+260'},
  {name: 'Zimbabwe', flag: '🇿🇼', code: 'ZW', dial_code: '+263'},
];

export const COUNTRY_PHONE_CODE = [
  {country: 'Afghanistan', code: '+93', iso: 'AF'},
  {country: 'Albania', code: '+355', iso: 'AL'},
  {country: 'Algeria', code: '+213', iso: 'DZ'},
  {country: 'American Samoa', code: '+1-684', iso: 'AS'},
  {country: 'Andorra', code: '+376', iso: 'AD'},
  {country: 'Angola', code: '+244', iso: 'AO'},
  {country: 'Anguilla', code: '+1-264', iso: 'AI'},
  {country: 'Antarctica', code: '+672', iso: 'AQ'},
  {country: 'Antigua and Barbuda', code: '+1-268', iso: 'AG'},
  {country: 'Argentina', code: '+54', iso: 'AR'},
  {country: 'Armenia', code: '+374', iso: 'AM'},
  {country: 'Aruba', code: '+297', iso: 'AW'},
  {country: 'Australia', code: '+61', iso: 'AU'},
  {country: 'Austria', code: '+43', iso: 'AT'},
  {country: 'Azerbaijan', code: '+994', iso: 'AZ'},
  {country: 'Bahamas', code: '+1-242', iso: 'BS'},
  {country: 'Bahrain', code: '+973', iso: 'BH'},
  {country: 'Bangladesh', code: '+880', iso: 'BD'},
  {country: 'Barbados', code: '+1-246', iso: 'BB'},
  {country: 'Belarus', code: '+375', iso: 'BY'},
  {country: 'Belgium', code: '+32', iso: 'BE'},
  {country: 'Belize', code: '+501', iso: 'BZ'},
  {country: 'Benin', code: '+229', iso: 'BJ'},
  {country: 'Bermuda', code: '+1-441', iso: 'BM'},
  {country: 'Bhutan', code: '+975', iso: 'BT'},
  {country: 'Bolivia', code: '+591', iso: 'BO'},
  {country: 'Bosnia and Herzegovina', code: '+387', iso: 'BA'},
  {country: 'Botswana', code: '+267', iso: 'BW'},
  {country: 'Brazil', code: '+55', iso: 'BR'},
  {country: 'British Indian Ocean Territory', code: '+246', iso: 'IO'},
  {country: 'British Virgin Islands', code: '+1-284', iso: 'VG'},
  {country: 'Brunei', code: '+673', iso: 'BN'},
  {country: 'Bulgaria', code: '+359', iso: 'BG'},
  {country: 'Burkina Faso', code: '+226', iso: 'BF'},
  {country: 'Burundi', code: '+257', iso: 'BI'},
  {country: 'Cambodia', code: '+855', iso: 'KH'},
  {country: 'Cameroon', code: '+237', iso: 'CM'},
  {country: 'Canada', code: '+1', iso: 'CA'},
  {country: 'Cape Verde', code: '+238', iso: 'CV'},
  {country: 'Central African Republic', code: '+236', iso: 'CF'},
  {country: 'Chad', code: '+235', iso: 'TD'},
  {country: 'Chile', code: '+56', iso: 'CL'},
  {country: 'China', code: '+86', iso: 'CN'},
  {country: 'Christmas Island', code: '+61', iso: 'CX'},
  {country: 'Cocos Islands', code: '+61', iso: 'CC'},
  {country: 'Colombia', code: '+57', iso: 'CO'},
  {country: 'Comoros', code: '+269', iso: 'KM'},
  {country: 'Cook Islands', code: '+682', iso: 'CK'},
  {country: 'Costa Rica', code: '+506', iso: 'CR'},
  {country: 'Croatia', code: '+385', iso: 'HR'},
  {country: 'Cuba', code: '+53', iso: 'CU'},
  {country: 'Curacao', code: '+599', iso: 'CW'},
  {country: 'Cyprus', code: '+357', iso: 'CY'},
  {country: 'Czech Republic', code: '+420', iso: 'CZ'},
  {country: 'Democratic Republic of the Congo', code: '+243', iso: 'CD'},
  {country: 'Denmark', code: '+45', iso: 'DK'},
  {country: 'Djibouti', code: '+253', iso: 'DJ'},
  {country: 'Dominica', code: '+1-767', iso: 'DM'},
  {country: 'East Timor', code: '+670', iso: 'TL'},
  {country: 'Ecuador', code: '+593', iso: 'EC'},
  {country: 'Egypt', code: '+20', iso: 'EG'},
  {country: 'El Salvador', code: '+503', iso: 'SV'},
  {country: 'Equatorial Guinea', code: '+240', iso: 'GQ'},
  {country: 'Eritrea', code: '+291', iso: 'ER'},
  {country: 'Estonia', code: '+372', iso: 'EE'},
  {country: 'Ethiopia', code: '+251', iso: 'ET'},
  {country: 'Falkland Islands', code: '+500', iso: 'FK'},
  {country: 'Faroe Islands', code: '+298', iso: 'FO'},
  {country: 'Fiji', code: '+679', iso: 'FJ'},
  {country: 'Finland', code: '+358', iso: 'FI'},
  {country: 'France', code: '+33', iso: 'FR'},
  {country: 'French Polynesia', code: '+689', iso: 'PF'},
  {country: 'Gabon', code: '+241', iso: 'GA'},
  {country: 'Gambia', code: '+220', iso: 'GM'},
  {country: 'Georgia', code: '+995', iso: 'GE'},
  {country: 'Germany', code: '+49', iso: 'DE'},
  {country: 'Ghana', code: '+233', iso: 'GH'},
  {country: 'Gibraltar', code: '+350', iso: 'GI'},
  {country: 'Greece', code: '+30', iso: 'GR'},
  {country: 'Greenland', code: '+299', iso: 'GL'},
  {country: 'Grenada', code: '+1-473', iso: 'GD'},
  {country: 'Guam', code: '+1-671', iso: 'GU'},
  {country: 'Guatemala', code: '+502', iso: 'GT'},
  {country: 'Guernsey', code: '+44-1481', iso: 'GG'},
  {country: 'Guinea', code: '+224', iso: 'GN'},
  {country: 'Guinea-Bissau', code: '+245', iso: 'GW'},
  {country: 'Guyana', code: '+592', iso: 'GY'},
  {country: 'Haiti', code: '+509', iso: 'HT'},
  {country: 'Honduras', code: '+504', iso: 'HN'},
  {country: 'Hong Kong', code: '+852', iso: 'HK'},
  {country: 'Hungary', code: '+36', iso: 'HU'},
  {country: 'Iceland', code: '+354', iso: 'IS'},
  {country: 'India', code: '+91', iso: 'IN'},
  {country: 'Indonesia', code: '+62', iso: 'ID'},
  {country: 'Iran', code: '+98', iso: 'IR'},
  {country: 'Iraq', code: '+964', iso: 'IQ'},
  {country: 'Ireland', code: '+353', iso: 'IE'},
  {country: 'Israel', code: '+972', iso: 'IL'},
  {country: 'Italy', code: '+39', iso: 'IT'},
  {country: 'Ivory Coast', code: '+225', iso: 'CI'},
  {country: 'Jamaica', code: '+1-876', iso: 'JM'},
  {country: 'Japan', code: '+81', iso: 'JP'},
  {country: 'Jersey', code: '+44-1534', iso: 'JE'},
  {country: 'Jordan', code: '+962', iso: 'JO'},
  {country: 'Kazakhstan', code: '+7', iso: 'KZ'},
  {country: 'Kenya', code: '+254', iso: 'KE'},
  {country: 'Kiribati', code: '+686', iso: 'KI'},
  {country: 'Kosovo', code: '+383', iso: 'XK'},
  {country: 'Kuwait', code: '+965', iso: 'KW'},
  {country: 'Kyrgyzstan', code: '+996', iso: 'KG'},
  {country: 'Laos', code: '+856', iso: 'LA'},
  {country: 'Latvia', code: '+371', iso: 'LV'},
  {country: 'Lebanon', code: '+961', iso: 'LB'},
  {country: 'Lesotho', code: '+266', iso: 'LS'},
  {country: 'Liberia', code: '+231', iso: 'LR'},
  {country: 'Libya', code: '+218', iso: 'LY'},
  {country: 'Liechtenstein', code: '+423', iso: 'LI'},
  {country: 'Lithuania', code: '+370', iso: 'LT'},
  {country: 'Luxembourg', code: '+352', iso: 'LU'},
  {country: 'Macao', code: '+853', iso: 'MO'},
  {country: 'Macedonia', code: '+389', iso: 'MK'},
  {country: 'Madagascar', code: '+261', iso: 'MG'},
  {country: 'Malawi', code: '+265', iso: 'MW'},
  {country: 'Malaysia', code: '+60', iso: 'MY'},
  {country: 'Maldives', code: '+960', iso: 'MV'},
  {country: 'Mali', code: '+223', iso: 'ML'},
  {country: 'Malta', code: '+356', iso: 'MT'},
  {country: 'Marshall Islands', code: '+692', iso: 'MH'},
  {country: 'Mauritania', code: '+222', iso: 'MR'},
  {country: 'Mauritius', code: '+230', iso: 'MU'},
  {country: 'Mayotte', code: '+262', iso: 'YT'},
  {country: 'Mexico', code: '+52', iso: 'MX'},
  {country: 'Micronesia', code: '+691', iso: 'FM'},
  {country: 'Moldova', code: '+373', iso: 'MD'},
  {country: 'Monaco', code: '+377', iso: 'MC'},
  {country: 'Mongolia', code: '+976', iso: 'MN'},
  {country: 'Montenegro', code: '+382', iso: 'ME'},
  {country: 'Montserrat', code: '+1-664', iso: 'MS'},
  {country: 'Morocco', code: '+212', iso: 'MA'},
  {country: 'Mozambique', code: '+258', iso: 'MZ'},
  {country: 'Myanmar', code: '+95', iso: 'MM'},
  {country: 'Namibia', code: '+264', iso: 'NA'},
  {country: 'Nauru', code: '+674', iso: 'NR'},
  {country: 'Nepal', code: '+977', iso: 'NP'},
  {country: 'Netherlands', code: '+31', iso: 'NL'},
  {country: 'Netherlands Antilles', code: '+599', iso: 'AN'},
  {country: 'New Caledonia', code: '+687', iso: 'NC'},
  {country: 'New Zealand', code: '+64', iso: 'NZ'},
  {country: 'Nicaragua', code: '+505', iso: 'NI'},
  {country: 'Niger', code: '+227', iso: 'NE'},
  {country: 'Nigeria', code: '+234', iso: 'NG'},
  {country: 'Niue', code: '+683', iso: 'NU'},
  {country: 'North Korea', code: '+850', iso: 'KP'},
  {country: 'Northern Mariana Islands', code: '+1-670', iso: 'MP'},
  {country: 'Norway', code: '+47', iso: 'NO'},
  {country: 'Oman', code: '+968', iso: 'OM'},
  {country: 'Pakistan', code: '+92', iso: 'PK'},
  {country: 'Palau', code: '+680', iso: 'PW'},
  {country: 'Palestine', code: '+970', iso: 'PS'},
  {country: 'Panama', code: '+507', iso: 'PA'},
  {country: 'Papua New Guinea', code: '+675', iso: 'PG'},
  {country: 'Paraguay', code: '+595', iso: 'PY'},
  {country: 'Peru', code: '+51', iso: 'PE'},
  {country: 'Philippines', code: '+63', iso: 'PH'},
  {country: 'Pitcairn', code: '+64', iso: 'PN'},
  {country: 'Poland', code: '+48', iso: 'PL'},
  {country: 'Portugal', code: '+351', iso: 'PT'},
  {country: 'Puerto Rico', code: '+1-787, 1-939', iso: 'PR'},
  {country: 'Qatar', code: '+974', iso: 'QA'},
  {country: 'Republic of the Congo', code: '+242', iso: 'CG'},
  {country: 'Reunion', code: '+262', iso: 'RE'},
  {country: 'Romania', code: '+40', iso: 'RO'},
  {country: 'Russia', code: '+7', iso: 'RU'},
  {country: 'Rwanda', code: '+250', iso: 'RW'},
  {country: 'Saint Barthelemy', code: '+590', iso: 'BL'},
  {country: 'Saint Helena', code: '+290', iso: 'SH'},
  {country: 'Saint Kitts and Nevis', code: '+1-869', iso: 'KN'},
  {country: 'Saint Lucia', code: '+1-758', iso: 'LC'},
  {country: 'Saint Martin', code: '+590', iso: 'MF'},
  {country: 'Saint Pierre and Miquelon', code: '+508', iso: 'PM'},
  {country: 'Samoa', code: '+685', iso: 'WS'},
  {country: 'San Marino', code: '+378', iso: 'SM'},
  {country: 'Sao Tome and Principe', code: '+239', iso: 'ST'},
  {country: 'Saudi Arabia', code: '+966', iso: 'SA'},
  {country: 'Senegal', code: '+221', iso: 'SN'},
  {country: 'Serbia', code: '+381', iso: 'RS'},
  {country: 'Seychelles', code: '+248', iso: 'SC'},
  {country: 'Sierra Leone', code: '+232', iso: 'SL'},
  {country: 'Singapore', code: '+65', iso: 'SG'},
  {country: 'Sint Maarten', code: '+1-721', iso: 'SX'},
  {country: 'Slovakia', code: '+421', iso: 'SK'},
  {country: 'Slovenia', code: '+386', iso: 'SI'},
  {country: 'Solomon Islands', code: '+677', iso: 'SB'},
  {country: 'Somalia', code: '+252', iso: 'SO'},
  {country: 'South Africa', code: '+27', iso: 'ZA'},
  {country: 'South Korea', code: '+82', iso: 'KR'},
  {country: 'South Sudan', code: '+211', iso: 'SS'},
  {country: 'Spain', code: '+34', iso: 'ES'},
  {country: 'Sri Lanka', code: '+94', iso: 'LK'},
  {country: 'Sudan', code: '+249', iso: 'SD'},
  {country: 'Suriname', code: '+597', iso: 'SR'},
  {country: 'Svalbard and Jan Mayen', code: '+47', iso: 'SJ'},
  {country: 'Swaziland', code: '+268', iso: 'SZ'},
  {country: 'Sweden', code: '+46', iso: 'SE'},
  {country: 'Switzerland', code: '+41', iso: 'CH'},
  {country: 'Syria', code: '+963', iso: 'SY'},
  {country: 'Taiwan', code: '+886', iso: 'TW'},
  {country: 'Tajikistan', code: '+992', iso: 'TJ'},
  {country: 'Tanzania', code: '+255', iso: 'TZ'},
  {country: 'Thailand', code: '+66', iso: 'TH'},
  {country: 'Togo', code: '+228', iso: 'TG'},
  {country: 'Tokelau', code: '+690', iso: 'TK'},
  {country: 'Tonga', code: '+676', iso: 'TO'},
  {country: 'Trinidad and Tobago', code: '+1-868', iso: 'TT'},
  {country: 'Tunisia', code: '+216', iso: 'TN'},
  {country: 'Turkey', code: '+90', iso: 'TR'},
  {country: 'Turkmenistan', code: '+993', iso: 'TM'},
  {country: 'Tuvalu', code: '+688', iso: 'TV'},
  {country: 'Uganda', code: '+256', iso: 'UG'},
  {country: 'Ukraine', code: '+380', iso: 'UA'},
  {country: 'United Arab Emirates', code: '+971', iso: 'AE'},
  {country: 'United Kingdom', code: '+44', iso: 'GB'},
  {country: 'United States', code: '+1', iso: 'US'},
  {country: 'Uruguay', code: '+598', iso: 'UY'},
  {country: 'Uzbekistan', code: '+998', iso: 'UZ'},
  {country: 'Vanuatu', code: '+678', iso: 'VU'},
  {country: 'Vatican', code: '+379', iso: 'VA'},
  {country: 'Venezuela', code: '+58', iso: 'VE'},
  {country: 'Vietnam', code: '+84', iso: 'VN'},
  {country: 'Wallis and Futuna', code: '+681', iso: 'WF'},
  {country: 'Western Sahara', code: '+212', iso: 'EH'},
  {country: 'Yemen', code: '+967', iso: 'YE'},
  {country: 'Zambia', code: '+260', iso: 'ZM'},
  {country: 'Zimbabwe', code: '+263', iso: 'ZW'},
];
